version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.1-jdk-11-slim
    working_directory: ~/clj-deps
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
