version: 2.1
jobs:
  test:
    docker:
      - image: maven:3.6.1-jdk-11-slim
    working_directory: ~/repo
    steps:
      - run:
          name: Install tools
          command: apt-get update && apt-get -yqq install git ssh
      - checkout
      - restore_cache:
          keys:
            - deps-cache-v1-{{ checksum "deps.edn" }}
            - deps-cache-v1-
      - run:
          name: Run tests
          command: mvn test
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: deps-cache-v1-{{ checksum "deps.edn" }}


workflows:
  version: 2
  ci:
    jobs:
      - test
