version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.1-jdk-11-slim
    working_directory: ~/repo
    steps:
      - run:
          name: Install tools
          command: apt-get update && apt-get -yqq install git ssh
      - checkout
      - run:
          name: Run tests
          command: mvn test
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
