version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.1-jdk-11-slim
    working_directory: ~/clj-deps
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Create `.ssh` directory
          command: mkdir ~/.ssh
      - run:
          name: Add `github.com` to `known_hosts`
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Run tests
          command: mvn test
