name: build

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'


jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: borkdude/clj-kondo
    steps:
      - uses: actions/checkout@v1
      - name: Run linter
        run: clj-kondo --lint src:test

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8', '11', '12', '13']
    name: Testing on java ${{ matrix.java }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.469'

      - name: Run clean
        run: make clean

      - name: Run tests
        run: make test

      - name: Run build
        run: make build
