name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run linter
        uses: DeLaGuardo/clojure-lint-action@v1
        with:
          clj-kondo-args: --lint src:test
          github_token: ${{ secrets.GITHUB_TOKEN }}


  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8', '11', '12', '13']
    name: Testing on java ${{ matrix.java }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest

      - name: Cache clojure deps
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clojure-

      - name: Run clean
        run: make clean

      - name: Run tests
        run: make test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/coverage/codecov.json


  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest

      - name: Cache clojure deps
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clojure-

      - name: Run clean
        run: make clean

      - name: Run build
        run: make build

      - name: Run deploy
        run: make deploy
